### ISSUE TITLE
Confusing about keypoints tracking

### ISSUE THREAD

**Issue by zhide730** [WangYixuan12/d3fields#1]
Thank you for your excellent work! I am confused about one part, why do you need to track keypoints from time t to t+1? Isn't the representation of the scene directly obtainable through observation at time t+1? Looking forward to your answer.

**Comment by WangYixuan12** [comment]
Hi Zhide, thank you for your interest in our work. You could directly obtain correspondence using observation at t+1. However, directly using it might be unstable. Therefore, leveraging the temporal information could make keypoint tracking more stable.
