### ISSUE TITLE
Info about visualization tool

### ISSUE THREAD

**Issue by AlbertoRemus** [WangYixuan12/d3fields#2]
Hi! really nice work, I particularly like the idea of driving manipulation with AI generated images

![Screenshot from 2023-10-13 12-08-46](https://github.com/WangYixuan12/d3fields/assets/54797872/f4aa138f-3f45-40a1-ac6e-2b521594da9a)

As depicted in the DinoV2 repo https://github.com/facebookresearch/dinov2/issues/23#issuecomment-1540475277 when we have a bunch of images of the same class to visualize similar parts with the same color it's needed to put them in the same "batch" and perform pca on the flattenized tensor (N x f), with f feature size

So to visualize the Goal image with the same color pattern of the point cloud you needed to perform PCA of the goal together with the other images or did u manage to achieve this directly (and how?)

Thanks in advance for your time!

**Comment by WangYixuan12** [comment]
Thank you for your interests in our work! For the PCA, we first fit the feature mapping for one type of object (e.g. shoe). We then use this precomputed PCA to transform high-dim features to lower dimension.

**Comment by AlbertoRemus** [comment]
@WangYixuan12 thanks for your reply! And how many instances did you use to compute the pca for one class?

**Comment by WangYixuan12** [comment]
I just use 4 images. I could upload PCA precomputation code later today.

**Comment by AlbertoRemus** [comment]
Ah that's great thank you!
