### ISSUE TITLE
Question about leveraging 3D information for the Query Image

### ISSUE THREAD

**Issue by AlbertoRemus** [WangYixuan12/d3fields#4]
Hi!

I have a question about the query image. Since it's RGB only, how can the 3D part of the features be leveraged to find 2D-3D correspondences? (in the block c of the figure)

![274870606-f4aa138f-3f45-40a1-ac6e-2b521594da9a](https://github.com/WangYixuan12/d3fields/assets/54797872/3613ea20-38f1-4c58-b255-4a4f5dce3e44)

**Comment by WangYixuan12** [comment]
We construct a reference camera here that can map 3D keypoints to 2D space to compute MSE Loss
