### ISSUE TITLE
About Truncation of Distance

### ISSUE THREAD

**Issue by XinchenYin** [WangYixuan12/d3fields#6]
Hello, I found that in Eq. 5 of your paper mentioned that d should be truncated to $[-\mu, \mu]$. But it seems that it will cause $w_i$ of Eq.6 to always be one and in your code I think there's no truncation in `eval_dist`. It confuses me a little bit.

**Comment by WangYixuan12** [comment]
Thank you for your question! We found that typo a while ago. We have fixed it in the latest arXiv. Please check it and let me know if you have more questions.
